// <auto-generated />
namespace FitApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FitAppUser_Changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FitAppUser_Changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201902261148410_FitAppUser_Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
