// <auto-generated />
namespace FitApp.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_table_Notification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_table_Notification));
        
        string IMigrationMetadata.Id
        {
            get { return "201903062102158_Add_table_Notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
